"""QuadStick preference (prefs.csv / Preferences sheet) vocabulary: 61 keys for
firmware 2373 with labels, units, ranges, defaults and plain-English descriptions.

Data derived from QuadStick Config Manager (Bbrizly, MIT License, Copyright (c)
2025 Brizly) src/QuadStick.Format/Data/preferences.json, itself sourced from the
QuadStick manual, QMP and the firmware headers. Only the data is reused; the
"source" provenance strings were dropped. `modeOverride` marks keys the firmware
accepts as a per-mode override row (column A = key, column C = value).
"""

PREFERENCES = {'joystick_deflection_maximum': {'label': 'Joystick sensitivity',
                                 'category': 'Joystick',
                                 'editor': 'integer',
                                 'default': '25',
                                 'minimum': 10,
                                 'maximum': 50,
                                 'description': 'How far the stick has to move for a full signal, '
                                                'also called full deflection. Lower is more '
                                                'sensitive, because a smaller push does the same '
                                                'thing.',
                                 'modeOverride': True},
 'joystick_deflection_minimum': {'label': 'Joystick center dead zone',
                                 'category': 'Joystick',
                                 'editor': 'integer',
                                 'default': '8',
                                 'minimum': 0,
                                 'maximum': 20,
                                 'description': 'How far the stick has to move before it counts. '
                                                'Larger is less sensitive near the center, which '
                                                'stops a resting stick drifting.',
                                 'modeOverride': True},
 'deflection_multiplier_up': {'label': 'Up deflection multiplier',
                              'category': 'Joystick',
                              'editor': 'integer',
                              'default': '140',
                              'unit': 'percent',
                              'description': 'Brings up level with the other directions. Larger is '
                                             'more sensitive going up.',
                              'modeOverride': True,
                              'advanced': True},
 'deflection_multiplier_down': {'label': 'Down deflection multiplier',
                                'category': 'Joystick',
                                'editor': 'integer',
                                'default': '130',
                                'unit': 'percent',
                                'description': 'Brings down level with the other directions. '
                                               'Larger is more sensitive going down.',
                                'modeOverride': True,
                                'advanced': True},
 'deflection_multiplier_left': {'label': 'Left deflection multiplier',
                                'category': 'Joystick',
                                'editor': 'integer',
                                'default': '100',
                                'unit': 'percent',
                                'description': 'Brings left level with the other directions. '
                                               'Larger is more sensitive going left.',
                                'modeOverride': True,
                                'advanced': True},
 'deflection_multiplier_right': {'label': 'Right deflection multiplier',
                                 'category': 'Joystick',
                                 'editor': 'integer',
                                 'default': '100',
                                 'unit': 'percent',
                                 'description': 'Brings right level with the other directions. '
                                                'Larger is more sensitive going right.',
                                 'modeOverride': True,
                                 'advanced': True},
 'joystick_D_Pad_inner': {'label': 'Inner D-Pad ring',
                          'category': 'Joystick',
                          'editor': 'integer',
                          'default': '25',
                          'minimum': 10,
                          'maximum': 100,
                          'unit': 'percent',
                          'description': 'Where the inner D-Pad ring starts, out from the center. '
                                         'It waits a moment first, so you can pass through it.',
                          'modeOverride': True,
                          'advanced': True},
 'joystick_D_Pad_outer': {'label': 'Outer D-Pad ring',
                          'category': 'Joystick',
                          'editor': 'integer',
                          'default': '80',
                          'minimum': 10,
                          'maximum': 100,
                          'unit': 'percent',
                          'description': 'Where the outer D-Pad ring starts, out from the center. '
                                         'Past this line the direction fires at once.',
                          'modeOverride': True,
                          'advanced': True},
 'joystick_dead_zone_shape': {'label': 'Circular dead zone',
                              'category': 'Joystick',
                              'editor': 'toggle',
                              'default': '1',
                              'description': 'Makes the center dead zone round instead of square, '
                                             'so it feels the same in every direction.',
                              'modeOverride': True,
                              'advanced': True},
 'anti_dead_zone': {'label': 'Anti dead zone',
                    'category': 'Joystick',
                    'editor': 'integer',
                    'default': '0',
                    'description': 'Adds a fixed push to every stick reading, in the direction the '
                                   'stick is pointing, to get past a dead zone the game adds of '
                                   'its own. Zero is off.',
                    'modeOverride': True,
                    'advanced': True},
 'joystick_warning': {'label': 'Joystick warning deflection',
                      'category': 'Joystick',
                      'editor': 'integer',
                      'default': '400',
                      'description': 'Your QuadStick ignores this. Older ones warned you here for '
                                     'pushing the stick too far.',
                      'modeOverride': True,
                      'advanced': True},
 'joystick_alarm': {'label': 'Joystick alarm deflection',
                    'category': 'Joystick',
                    'editor': 'integer',
                    'default': '500',
                    'description': 'Your QuadStick ignores this. Older ones sounded an alarm here '
                                   'for pushing the stick too far.',
                    'modeOverride': True,
                    'advanced': True},
 'enable_auto_zero': {'label': 'Auto zero the sensors',
                      'category': 'Joystick',
                      'editor': 'toggle',
                      'default': '0',
                      'description': 'Your QuadStick ignores this and forces it back to off.',
                      'modeOverride': True,
                      'advanced': True},
 'sip_puff_threshold_soft': {'label': 'Soft sip/puff threshold',
                             'category': 'Sip and puff',
                             'editor': 'integer',
                             'default': '8',
                             'minimum': 5,
                             'maximum': 100,
                             'unit': 'percent',
                             'description': 'Pressure where a soft sip or puff starts to count. '
                                            'Lower it if soft sips take too much breath.',
                             'modeOverride': True},
 'sip_puff_threshold': {'label': 'Normal sip/puff threshold',
                        'category': 'Sip and puff',
                        'editor': 'integer',
                        'default': '40',
                        'minimum': 10,
                        'maximum': 100,
                        'unit': 'percent',
                        'description': 'Pressure where a normal sip or puff counts. QMP calls this '
                                       'the hard threshold, but it is what the ordinary sip and '
                                       'puff controls use. Raise it if soft sips keep firing the '
                                       'normal one.',
                        'modeOverride': True},
 'sip_puff_delay_soft': {'label': 'Soft sip/puff delay',
                         'category': 'Sip and puff',
                         'editor': 'integer',
                         'default': '1300',
                         'minimum': 100,
                         'maximum': 3000,
                         'unit': 'milliseconds',
                         'description': 'How long a soft sip or puff waits before it counts. '
                                        'Longer ignores a breath you did not mean.',
                         'modeOverride': True},
 'sip_puff_delay_hard': {'label': 'Hard sip/puff delay',
                         'category': 'Sip and puff',
                         'editor': 'integer',
                         'default': '2000',
                         'minimum': 1000,
                         'maximum': 3000,
                         'unit': 'milliseconds',
                         'description': 'How long you hold a sip or puff before it counts as a '
                                        'long one. On the side tube that is how long you sip to '
                                        'switch game files. The clock starts at the normal '
                                        'threshold, and 0 fires at once.',
                         'modeOverride': True},
 'sip_puff_maximum': {'label': 'Sip/puff maximum pressure',
                      'category': 'Sip and puff',
                      'editor': 'integer',
                      'default': '70',
                      'minimum': 10,
                      'maximum': 100,
                      'unit': 'percent',
                      'description': 'Pressure that gives a full signal. Lower it if you cannot '
                                     'reach full strength.',
                      'modeOverride': True,
                      'advanced': True},
 'sip_threshold_soft': {'label': 'Soft sip threshold',
                        'category': 'Sip and puff',
                        'editor': 'integer',
                        'default': '0',
                        'minimum': 0,
                        'maximum': 100,
                        'unit': 'percent',
                        'description': 'Soft threshold for sips only. Leave it at 0 to use the '
                                       'shared soft threshold.',
                        'modeOverride': True,
                        'advanced': True},
 'sip_threshold': {'label': 'Normal sip threshold',
                   'category': 'Sip and puff',
                   'editor': 'integer',
                   'default': '0',
                   'minimum': 0,
                   'maximum': 100,
                   'unit': 'percent',
                   'description': 'Normal threshold for sips only. Leave it at 0 to use the shared '
                                  'normal threshold.',
                   'modeOverride': True,
                   'advanced': True},
 'sip_maximum': {'label': 'Sip maximum vacuum',
                 'category': 'Sip and puff',
                 'editor': 'integer',
                 'default': '0',
                 'minimum': 0,
                 'maximum': 100,
                 'unit': 'percent',
                 'description': 'Full signal point for sips only. Leave it at 0 to use the shared '
                                'maximum.',
                 'modeOverride': True,
                 'advanced': True},
 'puff_threshold_soft': {'label': 'Soft puff threshold',
                         'category': 'Sip and puff',
                         'editor': 'integer',
                         'default': '0',
                         'minimum': 0,
                         'maximum': 100,
                         'unit': 'percent',
                         'description': 'Soft threshold for puffs only. Leave it at 0 to use the '
                                        'shared soft threshold.',
                         'modeOverride': True,
                         'advanced': True},
 'puff_threshold': {'label': 'Normal puff threshold',
                    'category': 'Sip and puff',
                    'editor': 'integer',
                    'default': '0',
                    'minimum': 0,
                    'maximum': 100,
                    'unit': 'percent',
                    'description': 'Normal threshold for puffs only. Leave it at 0 to use the '
                                   'shared normal threshold.',
                    'modeOverride': True,
                    'advanced': True},
 'puff_maximum': {'label': 'Puff maximum pressure',
                  'category': 'Sip and puff',
                  'editor': 'integer',
                  'default': '0',
                  'minimum': 0,
                  'maximum': 100,
                  'unit': 'percent',
                  'description': 'Full signal point for puffs only. Leave it at 0 to use the '
                                 'shared maximum.',
                  'modeOverride': True,
                  'advanced': True},
 'enable_left_side_tube': {'label': 'Use the left side tube',
                           'category': 'Sip and puff',
                           'editor': 'toggle',
                           'default': '0',
                           'description': 'Swaps the side tubes so the left one does mode control, '
                                          'for people who reach the left more easily.',
                           'modeOverride': True,
                           'advanced': True},
 'lip_position_minimum': {'label': 'Lip sensor minimum',
                          'category': 'Lip sensor',
                          'editor': 'integer',
                          'default': '8',
                          'minimum': 5,
                          'maximum': 100,
                          'unit': 'percent',
                          'description': 'How far the lip plate has to move before it counts. '
                                         'Raise it if it fires when you rest your lip.',
                          'modeOverride': True},
 'lip_position_maximum': {'label': 'Lip sensor maximum',
                          'category': 'Lip sensor',
                          'editor': 'integer',
                          'default': '35',
                          'minimum': 5,
                          'maximum': 100,
                          'unit': 'percent',
                          'description': 'How far the lip plate moves for a full signal. Lower it '
                                         'if you cannot reach full strength.',
                          'modeOverride': True},
 'mouse_speed': {'label': 'Mouse speed',
                 'category': 'Mouse',
                 'editor': 'integer',
                 'default': '100',
                 'minimum': 0,
                 'maximum': 250,
                 'description': 'How fast the pointer moves for the same push on the stick.',
                 'modeOverride': True},
 'mouse_response_curve': {'label': 'Mouse response curve',
                          'category': 'Mouse',
                          'editor': 'choice',
                          'default': '1',
                          'description': 'How a push turns into pointer speed. Parabolic gives '
                                         'fine control near the center and speed at the edge.',
                          'modeOverride': True,
                          'options': ['0', '1', '2'],
                          # named in the manual's mouse section; the other numeric
                          # choices below are left bare because nothing we have
                          # documents what each of their numbers means
                          'optionLabels': {'0': 'Linear',
                                           '1': 'Parabolic',
                                           '2': 'Steeper parabolic'}},
 'volume': {'label': 'Speaker volume',
            'category': 'Sound and lights',
            'editor': 'integer',
            'default': '40',
            'minimum': 0,
            'maximum': 100,
            'description': "How loud the QuadStick's own beeps are.",
            'modeOverride': True},
 'brightness': {'label': 'LED brightness',
                'category': 'Sound and lights',
                'editor': 'integer',
                'default': '75',
                'minimum': 0,
                'maximum': 100,
                'description': 'How bright the mode lights on the case are.',
                'modeOverride': True},
 'enable_rumble': {'label': 'Rumble',
                   'category': 'Sound and lights',
                   'editor': 'toggle',
                   'default': '0',
                   'description': "In DualShock 3 mode only, plays the game's rumble as a tone on "
                                  "the QuadStick's own speaker.",
                   'modeOverride': True},
 'bluetooth_device_mode': {'label': 'Bluetooth device mode',
                           'category': 'Bluetooth',
                           'editor': 'choice',
                           'default': 'none',
                           'description': 'What the QuadStick pretends to be over Bluetooth.',
                           'modeOverride': True,
                           'options': ['none',
                                       'keyboard',
                                       'game_pad',
                                       'mouse',
                                       'combo',
                                       'joystick',
                                       'ssp']},
 'bluetooth_authentication_mode': {'label': 'Bluetooth authentication mode',
                                   'category': 'Bluetooth',
                                   'editor': 'choice',
                                   'default': '2',
                                   'description': 'How much pairing the QuadStick asks for. Sent '
                                                  'to the radio as its SA setting, so it only '
                                                  'matters while Bluetooth is on.',
                                   'modeOverride': True,
                                   'options': ['0', '1', '2', '4']},
 'bluetooth_connection_mode': {'label': 'Bluetooth connection mode',
                               'category': 'Bluetooth',
                               'editor': 'choice',
                               'default': 'pair',
                               'description': 'Whether the QuadStick waits to be connected to or '
                                              'connects out itself. Sent to the radio as its SM '
                                              'setting.',
                               'modeOverride': True,
                               'options': ['slave',
                                           'master',
                                           'trigger',
                                           'auto',
                                           'dtr',
                                           'any',
                                           'pair']},
 'bluetooth_remote_address': {'label': 'Bluetooth remote address',
                              'category': 'Bluetooth',
                              'editor': 'text',
                              'default': '',
                              'description': 'The Bluetooth address the QuadStick connects out to. '
                                             'Leave it empty unless QuadStick support gave you '
                                             'one. Sixteen characters at most.',
                              'modeOverride': True,
                              'advanced': True},
 'bluetooth_remote_adapter': {'label': 'Bluetooth remote adapter',
                              'category': 'Bluetooth',
                              'editor': 'toggle',
                              'default': '0',
                              'description': 'Makes the QuadStick a Bluetooth adapter for '
                                             'something else. It stops reading its own mouthpiece '
                                             'and stick while this is on and the Bluetooth device '
                                             'mode is ssp.',
                              'modeOverride': True,
                              'advanced': True},
 'bluetooth_throttle': {'label': 'Bluetooth throttle',
                        'category': 'Bluetooth',
                        'editor': 'integer',
                        'default': '5',
                        'description': 'Smallest gap the QuadStick leaves between Bluetooth sends.',
                        'modeOverride': True,
                        'advanced': True},
 'digital_out_1': {'label': 'Digital output 1',
                   'category': 'Inputs and outputs',
                   'editor': 'toggle',
                   'default': '0',
                   'description': 'Turns output jack 1 on or off. A mode cannot change it.',
                   'modeOverride': False},
 'digital_out_2': {'label': 'Digital output 2',
                   'category': 'Inputs and outputs',
                   'editor': 'toggle',
                   'default': '0',
                   'description': 'Turns output jack 2 on or off. A mode cannot change it.',
                   'modeOverride': False},
 'digital_out_3': {'label': 'Digital output 3',
                   'category': 'Inputs and outputs',
                   'editor': 'toggle',
                   'default': '0',
                   'description': 'Turns output jack 3 on or off. A mode cannot change it.',
                   'modeOverride': False},
 'digital_out_4': {'label': 'Digital output 4',
                   'category': 'Inputs and outputs',
                   'editor': 'toggle',
                   'default': '0',
                   'description': 'Turns output jack 4 on or off. A mode cannot change it.',
                   'modeOverride': False},
 'enable_swap_inputs': {'label': 'Swap inputs with the side tube',
                        'category': 'Inputs and outputs',
                        'editor': 'toggle',
                        'default': '0',
                        'description': 'Lets the side tube swap your inputs over.',
                        'modeOverride': True},
 'enable_select_files': {'label': 'Select files with the side tube',
                         'category': 'Inputs and outputs',
                         'editor': 'toggle',
                         'default': '1',
                         'description': 'Lets the side tube pick which profile file the QuadStick '
                                        'loads.',
                         'modeOverride': True},
 'enable_usb_a_host': {'label': 'USB-A host mode',
                       'category': 'USB and compatibility',
                       'editor': 'toggle',
                       'default': '1',
                       'description': 'Newer QuadSticks only. Lets a controller plugged into the '
                                      'USB-A port feed the USB 1 and USB 2 inputs, unless USB-A '
                                      'device mode is on.',
                       'modeOverride': True},
 'enable_DS3_emulation': {'label': 'USB emulation mode',
                          'category': 'USB and compatibility',
                          'editor': 'choice',
                          'default': '0',
                          'description': 'Which controller the QuadStick pretends to be. The '
                                         'console has to know the one you pick. Modes 2 and 3 are '
                                         'both Xbox on a PC and they are not the same trade. On '
                                         'mode 2 the QuadStick is a plain gamepad, and a program '
                                         'on the computer has to turn it into an Xbox controller: '
                                         'QuadStick Manager does this while it is open, and x360ce '
                                         'does it per game. With neither running, a game asking '
                                         'you to press A sees no controller at all. Mode 3 needs '
                                         'nothing running, because the QuadStick reports itself as '
                                         'a real Xbox 360 controller, but that is the only thing '
                                         'it offers on that mode: no keyboard, no mouse and no '
                                         'drive.',
                          'modeOverride': True,
                          'options': ['0', '1', '2', '3', '4', '5', '6', '7']},
 'titan_two': {'label': 'Titan Two adapter',
               'category': 'USB and compatibility',
               'editor': 'toggle',
               'default': '0',
               'description': 'Newer QuadSticks only. Tells the QuadStick it reaches a PS4 through '
                              'a Titan Two. Turn it on only if you use one.',
               'modeOverride': True},
 'enable_usb_a_device': {'label': 'USB-A device mode',
                         'category': 'USB and compatibility',
                         'editor': 'integer',
                         'default': '0',
                         'description': 'Which USB socket the QuadStick appears on. Zero is its '
                                        'own port; above zero is the USB-A socket, and that also '
                                        'turns off USB-A host mode.',
                         'modeOverride': True,
                         'advanced': True},
 'enable_usb_comm': {'label': 'Voice commands over USB',
                     'category': 'USB and compatibility',
                     'editor': 'toggle',
                     'default': '0',
                     'description': 'Lets voice commands arrive over the USB cable.',
                     'modeOverride': True,
                     'advanced': True},
 'usb_1_multiplier_up': {'label': 'USB 1 up multiplier',
                         'category': 'USB and compatibility',
                         'editor': 'integer',
                         'default': '100',
                         'description': 'Boosts up on the left stick of a controller plugged into '
                                        'the USB-A port.',
                         'modeOverride': True,
                         'advanced': True},
 'usb_1_multiplier_down': {'label': 'USB 1 down multiplier',
                           'category': 'USB and compatibility',
                           'editor': 'integer',
                           'default': '100',
                           'description': 'Boosts down on the left stick of a controller plugged '
                                          'into the USB-A port.',
                           'modeOverride': True,
                           'advanced': True},
 'usb_1_multiplier_left': {'label': 'USB 1 left multiplier',
                           'category': 'USB and compatibility',
                           'editor': 'integer',
                           'default': '100',
                           'description': 'Boosts left on the left stick of a controller plugged '
                                          'into the USB-A port.',
                           'modeOverride': True,
                           'advanced': True},
 'usb_1_multiplier_right': {'label': 'USB 1 right multiplier',
                            'category': 'USB and compatibility',
                            'editor': 'integer',
                            'default': '100',
                            'description': 'Boosts right on the left stick of a controller plugged '
                                           'into the USB-A port.',
                            'modeOverride': True,
                            'advanced': True},
 'usb_2_multiplier_up': {'label': 'USB 2 up multiplier',
                         'category': 'USB and compatibility',
                         'editor': 'integer',
                         'default': '100',
                         'description': 'Boosts up on the right stick of a controller plugged into '
                                        'the USB-A port.',
                         'modeOverride': True,
                         'advanced': True},
 'usb_2_multiplier_down': {'label': 'USB 2 down multiplier',
                           'category': 'USB and compatibility',
                           'editor': 'integer',
                           'default': '100',
                           'description': 'Boosts down on the right stick of a controller plugged '
                                          'into the USB-A port.',
                           'modeOverride': True,
                           'advanced': True},
 'usb_2_multiplier_left': {'label': 'USB 2 left multiplier',
                           'category': 'USB and compatibility',
                           'editor': 'integer',
                           'default': '100',
                           'description': 'Boosts left on the right stick of a controller plugged '
                                          'into the USB-A port.',
                           'modeOverride': True,
                           'advanced': True},
 'usb_2_multiplier_right': {'label': 'USB 2 right multiplier',
                            'category': 'USB and compatibility',
                            'editor': 'integer',
                            'default': '100',
                            'description': 'Boosts right on the right stick of a controller '
                                           'plugged into the USB-A port.',
                            'modeOverride': True,
                            'advanced': True},
 'usb_1_dead_zone': {'label': 'USB 1 dead zone',
                     'category': 'USB and compatibility',
                     'editor': 'integer',
                     'default': '20',
                     'unit': 'raw axis counts',
                     'description': 'Newer QuadSticks only. Dead zone for a controller on the '
                                    'USB-A port, counted in raw axis steps rather than percent. '
                                    '128 or more kills the axis.',
                     'modeOverride': True,
                     'advanced': True},
 'usb_2_dead_zone': {'label': 'USB 2 dead zone',
                     'category': 'USB and compatibility',
                     'editor': 'integer',
                     'default': '20',
                     'unit': 'raw axis counts',
                     'description': 'Newer QuadSticks only, and your QuadStick ignores it anyway: '
                                    'both sticks on the USB-A port use the USB 1 dead zone.',
                     'modeOverride': True,
                     'advanced': True},
 'watchdog_disable': {'label': 'Disable the watchdog',
                      'category': 'Advanced',
                      'editor': 'toggle',
                      'default': '0',
                      'description': 'Was meant to stop the QuadStick restarting itself when it '
                                     'locks up. Your QuadStick ignores it.',
                      'modeOverride': True},
 'debug': {'label': 'Debug output level',
           'category': 'Advanced',
           'editor': 'integer',
           'default': '1',
           'description': "Any value above zero turns the QuadStick's console output on.",
           'modeOverride': True}}

CATEGORIES = list(dict.fromkeys(p["category"] for p in PREFERENCES.values()))
MODE_OVERRIDABLE = {k for k, p in PREFERENCES.items() if p.get("modeOverride")}

# Pairs the firmware needs in order: (lower key, minimum gap, higher key, zero_means_unset).
# It divides by (maximum - threshold) and tells soft from normal by the gap; QCM
# enforces the same distances. Per-direction sip/puff keys use 0 for "use the
# shared value", so a 0 on either side is not compared.
THRESHOLD_ORDER = [
    ("sip_puff_threshold_soft", 2, "sip_puff_threshold", False),
    ("sip_puff_threshold", 2, "sip_puff_maximum", False),
    ("lip_position_minimum", 5, "lip_position_maximum", False),
    ("joystick_D_Pad_inner", 2, "joystick_D_Pad_outer", False),
    ("sip_threshold_soft", 2, "sip_threshold", True),
    ("sip_threshold", 2, "sip_maximum", True),
    ("puff_threshold_soft", 2, "puff_threshold", True),
    ("puff_threshold", 2, "puff_maximum", True),
]
